apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-listener-lb
  labels:
      app: pod-snmp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: pod-snmp
  ports:
    - protocol: UDP
      port: 39000
      targetPort: 9000
      name: snmp-udp
    - protocol: TCP
      port: 39000
      targetPort: 9000
      name: snmp-tcp
  externalIPs:
    - 10.198.7.150
