apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-listener-lb
spec:
  selector:
    app: pod-snmp
  ports:
    - protocol: UDP
      port: 39000
      targetPort: 9000
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  externalIPs:
    - 10.198.7.150