apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-listener-nodeport
  labels:
    app: pod-snmp
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: pod-snmp
  ports:
    - protocol: UDP
      port: 9000
      targetPort: 9000
      nodePort: 30900
      name: snmp-udp
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
      name: snmp-tcp